// Code generated by protoc-gen-go. DO NOT EDIT.
// source: auth.proto

package proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetJwtRequest struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJwtRequest) Reset()         { *m = GetJwtRequest{} }
func (m *GetJwtRequest) String() string { return proto.CompactTextString(m) }
func (*GetJwtRequest) ProtoMessage()    {}
func (*GetJwtRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{0}
}

func (m *GetJwtRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJwtRequest.Unmarshal(m, b)
}
func (m *GetJwtRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJwtRequest.Marshal(b, m, deterministic)
}
func (m *GetJwtRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJwtRequest.Merge(m, src)
}
func (m *GetJwtRequest) XXX_Size() int {
	return xxx_messageInfo_GetJwtRequest.Size(m)
}
func (m *GetJwtRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJwtRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetJwtRequest proto.InternalMessageInfo

func (m *GetJwtRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type GetJwtResponse struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJwtResponse) Reset()         { *m = GetJwtResponse{} }
func (m *GetJwtResponse) String() string { return proto.CompactTextString(m) }
func (*GetJwtResponse) ProtoMessage()    {}
func (*GetJwtResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8bbd6f3875b0e874, []int{1}
}

func (m *GetJwtResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJwtResponse.Unmarshal(m, b)
}
func (m *GetJwtResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJwtResponse.Marshal(b, m, deterministic)
}
func (m *GetJwtResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJwtResponse.Merge(m, src)
}
func (m *GetJwtResponse) XXX_Size() int {
	return xxx_messageInfo_GetJwtResponse.Size(m)
}
func (m *GetJwtResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJwtResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetJwtResponse proto.InternalMessageInfo

func (m *GetJwtResponse) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func init() {
	proto.RegisterType((*GetJwtRequest)(nil), "GetJwtRequest")
	proto.RegisterType((*GetJwtResponse)(nil), "GetJwtResponse")
}

func init() { proto.RegisterFile("auth.proto", fileDescriptor_8bbd6f3875b0e874) }

var fileDescriptor_8bbd6f3875b0e874 = []byte{
	// 124 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0x2c, 0x2d, 0xc9,
	0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe6, 0xe2, 0x75, 0x4f, 0x2d, 0xf1, 0x2a, 0x2f,
	0x09, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe2, 0x62, 0x49, 0xce, 0x4f, 0x49, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x95, 0x94, 0xb8, 0xf8, 0x60, 0x8a, 0x8a, 0x0b,
	0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x04, 0xb8, 0x98, 0xb3, 0xca, 0x4b, 0xa0, 0x8a, 0x40, 0x4c, 0x23,
	0x63, 0x2e, 0x16, 0xc7, 0xd2, 0x92, 0x0c, 0x21, 0x6d, 0x2e, 0x36, 0x88, 0x5a, 0x21, 0x3e, 0x3d,
	0x14, 0x93, 0xa5, 0xf8, 0xf5, 0x50, 0x0d, 0x51, 0x62, 0x48, 0x62, 0x03, 0x3b, 0xc2, 0x18, 0x10,
	0x00, 0x00, 0xff, 0xff, 0xe7, 0x1d, 0x68, 0x57, 0x92, 0x00, 0x00, 0x00,
}
