// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: auth.proto

package proto

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"

	context "context"

	client "github.com/micro/go-micro/client"

	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Auth service

type AuthService interface {
	GetJwt(ctx context.Context, in *GetJwtRequest, opts ...client.CallOption) (*GetJwtResponse, error)
}

type authService struct {
	c    client.Client
	name string
}

func NewAuthService(name string, c client.Client) AuthService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "auth"
	}
	return &authService{
		c:    c,
		name: name,
	}
}

func (c *authService) GetJwt(ctx context.Context, in *GetJwtRequest, opts ...client.CallOption) (*GetJwtResponse, error) {
	req := c.c.NewRequest(c.name, "Auth.GetJwt", in)
	out := new(GetJwtResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Auth service

type AuthHandler interface {
	GetJwt(context.Context, *GetJwtRequest, *GetJwtResponse) error
}

func RegisterAuthHandler(s server.Server, hdlr AuthHandler, opts ...server.HandlerOption) error {
	type auth interface {
		GetJwt(ctx context.Context, in *GetJwtRequest, out *GetJwtResponse) error
	}
	type Auth struct {
		auth
	}
	h := &authHandler{hdlr}
	return s.Handle(s.NewHandler(&Auth{h}, opts...))
}

type authHandler struct {
	AuthHandler
}

func (h *authHandler) GetJwt(ctx context.Context, in *GetJwtRequest, out *GetJwtResponse) error {
	return h.AuthHandler.GetJwt(ctx, in, out)
}
